shop/ecommerceproject/Cart/urls.py
from django.urls import path
from . import views

app_name = 'Cart'
urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name="add_cart"),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name="cart_remove"),

]

shop/ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('Cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/ecommerceproject/search_app/urls.py
from django.urls import path
from . import views

app_name = 'search_app'
urlpatterns = [
    path('', views.SearchResult, name="SearchResult"),
]

shop/ecommerceproject/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.allProdCat, name="allProdCat"),
    path('home/<slug:c_slug>/', views.allProdCat, name="product_by_category"),
    path('home/<slug:c_slug>/<slug:product_slug>/', views.proDetail, name="product_by_category")
]

shop/ecommerceproject/Cart/models.py
from django.db import models
from shop.models import Product


# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

shop/ecommerceproject/search_app/models.py
from django.db import models

# Create your models here.

shop/ecommerceproject/shop/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shop:product_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('shop:product_by_category', args=[self.category.slug, self.slug])

    def __str__(self):
        return '{}'.format(self.name)

shop/ecommerceproject/Cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
        cart_item.save()
    return redirect('Cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('Cart:cart_detail')

shop/ecommerceproject/search_app/views.py
from shop.models import Product
from django.db.models import Q
from django.shortcuts import render


# Create your views here.

def SearchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request, 'search.html', {'query': query, 'products': products})

shop/ecommerceproject/shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Category, Product
from django.core.paginator import Paginator, InvalidPage, EmptyPage


def allProdCat(request, c_slug=None):
    c_page = None
    products_list = None
    if (c_slug != None):
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator = Paginator(products_list, 6)
    try:
            page = int(request.GET.get('page', 1))
    except:
            page = 1
    try:
            products = paginator.page(page)
    except (EmptyPage, InvalidPage):
            products = paginator.page(paginator.num_pages)

    return render(request, "category.html", {'category': c_page, 'products': products})

def proDetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product': product})

shop/ecommerceproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel = "stylesheet" href="{% static 'css/custom.css' %}">
    <link href ="{% static 'css/bootstrap.min.css' %}"  rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/f67ae3eab0.js" crossorigin="anonymous"></script>
    <meta name = "description" content = "{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div>
    {% include 'header.html' %}
    {% include 'navbar.html' %}
<!--    {% include 'nav.html' %}-->
    {% block content %}
    {% endblock %}
</div>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% include 'footer.html' %}
</body>
</html>

shop/ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
We have a variety of car products that are fully equipped with security features.
{% endblock %}
{% block title %}
Cart Items
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class = "text-center">
        <br>
        <h1 class = "text-center my_title">
            Your Shopping Cart is Empty
        </h1>
        <br>
        <p class="text-center">
        <a href="{% url 'shop:allProdCat' %}" class="my-link" title="Continue Shopping">Please click here to continue shopping</p>
    </div>
</div>
{% else %}
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">
                  Your Item
               </th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get.absolute_url"><img src="{{cart_item.product.image.url}}" height=100px; class="float-left rounded custom_image"></a>
                </td>
                <td class="text-left">
                    {{cart_item.product.name}}
                 <br>
                    SKU:{{cart_item.product.id}}
                  <br>
                    Price:${{cart_item.product.price}}
                   <br>
                    Qty:{{cart_item.quantity}} * $ {{cart_item}}
                    <br>
                  </td>
                  <td>
                      {{cart_item.sub_total}}
                </td>
                     {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'Cart:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fa-sharp fa-solid fa-plus"></i>

                    &nbsp; <a href="{% url 'Cart:cart_remove' cart_item.product.id %}" class="custom_a"> <i class="fa-regular fa-minus"></i></a>
                    &nbsp; <a href="{% url 'Cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-sharp fa-solid fa-trash"></i></a>
                </td>
                     {% else %}
                <td>
                     &nbsp; <a href="{% url 'Cart:cart_remove' cart_item.product.id %}" class="custom_a" <i class="fa-regular fa-minus"></i></a>
                     &nbsp; <a href="{% url 'Cart:cart_remove' cart_item.product.id %}" class="custom_a" <i class="fa-sharp fa-solid fa-trash"></i></a>
                </td>
                     {% endif %}
            </tr>
                     {% endfor %}
            </tbody>

        </table>
    </div>
    <div class ="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
             <tr>
                 <th>
                     CHECKOUT
                 </th>
             </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Total is : <strong>{{total}}</strong>
                </td>
            </tr>
            <tr>
                <td>
                    Please review your shopping cart items before proceeding to the payment.
                </td>
            </tr>
            </tbody>
            </table>
            <div class="mx-auto">
                <a href="{% url 'shop:allProdCat' %}" class="btn btn-secondary btn-block my_custom_table">Continue Shopping</a>
            </div>
           {% endif %}
{% endblock %}

shop/ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   {% if category %}
     {{category.description|truncatewords:155}}
   {% else %}
     Nothing to show
   {% endif %}
{% endblock %}
{% block title %}
   {% if category %}
       {{category.name}}
   {% else %}
      Car Showroom
    {% endif %}
{% endblock %}
{% block content %}
   {% if category %}
       <div class = "row my_row_class">
           <div class = "mx_auto">
           <p><a href = "{% url 'shop:allProdCat' %}">All Products</a></p>
       </div>
   </div>
   {% endif %}
   {% if category %}
   <div class = "container">
   <div class = "row">
        <img class ="my_image" src = "{{category.image.url}}" alt = "{{category.name}}">
   </div>
   </div>
     <br>
   <div>
   <h1 class="text-center">{{category.name}}</h1>
       <h3 class="text-justify">{{category.description}}</h3>
   </div>
   <br>
   {% else %}
   <div class = "container">
       <div class ="row">
       <img class="my_image my_image_padding" src = "{% static 'img/banner.png' %}" alt="all products" width="362px;" height="362px;" >
   </div>
   </div>
   <div class ="container">
       <div class = "row">
       <h1 class ="text-center my_title"> Our Products </h1>
       <p class ="text-justify">For brands, the shoppable content definition means when you take content (posts) that features products, and you tag those products with checkout link, price, details, etc., so that users can buy those products directly from the posts.</p>
       </div>
   </div>
<br>
   {% endif %}

  <div class ="container text-center">
      <div class ="row mx_auto">
          {% for product in products %}
          <div class = "my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
          <div class="card text-center" style="min-width:18rem;">
              <a href ="{{product.get_url}}"> <img class = "card-img-top my_image" src = "{{product.image.url}}" height="242px;" width="242px;" alt="all products"></a>
                       <div class = "card-body">
                       <h4><b> {{product.name}}</b></h4>
                       <h4><b>{{product.price}}</b></h4>
                      </div>
                </div>
          </div>
          {% endfor %}
      </div>
      <div class = "mx_auto">
          {% if products.paginator.num_pages > 1 %}

         <br>
      <div class = "text-center">
           {% for pg in products.paginator.page_range %}
           <a href = "?page={{pg}}" class ="btn btn-light btn-sm" "{% if products.number == pg %} active {% endif %}">{{pg}}</a>
           {% endfor %}
       </div>
          {% endif %}
  </div>
  </div>

{% endblock %}

shop/ecommerceproject/templates/footer.html
{% load static %}
<div class="footer navbar-fixed-bottom my_footer text-center">
  Copyright © ABC Private Limited. All Rights Reserved.
</div>

shop/ecommerceproject/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'shop:allProdCat' %}"></a><img src = "{% static 'img/carshop.png' %}" alt="logimage" width="152px;" height="152px;">
    </center>
</header>

shop/ecommerceproject/templates/nav.html
<nav>
    <ul>
        <li><a href="{% url 'shop:allProdCat' %}">ALL PRODUCTS</a></li>
        {% for cat in links %}
        <li><a href="{{cat.get_url}}">{{cat.name}}</a></li>
        {% endfor %}
        <li>Your Cart()</li>
    </ul>
</nav>

shop/ecommerceproject/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:allProdCat' %}">Home</a>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Cart:cart_detail' %}">{{item_count}}<i class="fa-solid fa-cart-shopping"></i></a>
        </li>
        {% endif %}

          <a class="nav-link dropdown-toggle" href="{% url 'shop:allProdCat' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            ALL PRODUCTS
          </a>
          <ul class="dropdown-menu">
            {% for product in products %}
            <li><a class="dropdown-item" href="{{product.get_url}}">{{product.name}}</a></li>
            {% endfor %}
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
      </ul>
      <form class="d-flex"  action = "{% url 'search_app:SearchResult' %}" method = "get" role="search">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name='q' aria-label="Search"
        <button class="btn btn-outline-success" type="submit"><i class="fa-regular fa-magnifying-glass-plus"></i></button>
      </form>
    </div>
  </div>
</nav>

shop/ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
     {{product.description|truncatewords:155}}
{% endblock %}
{% block title %}
   {% if product %}
       {{product.name}}
   {% endif %}
{% endblock %}
{% block content %}
  <div class="row my_prod_row_class">
    <div class = "mx_auto">
      <p><a href ="{% url 'shop:allProdCat' %}">Home</a>|<a href="{product.category.get_url}">{{product.category.name}}</a>|<a href="{product.get_url}"></a>{{product.name}}</p>
    </div>
  </div>
  <div class= "container">
    <div class = "row">
      <div class = "col-md-12 col-sm-12 col-md-12 col-lg-12 text-center">
        <div style = "min-width:18rem;">
        <img src = "{{product.image.url}}" alt="{{product.name}}" width = "300px" height = "300px">
    </div>
  </div>
  <div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-12 text-center">
      <h2 class = "my_prod_title">{{product.name}}</h2>
      <p class = "my_title">My Product</p>
      <p class ="text-justify my_rod_text">{{product.description}}</p>
      <h3>{% if product.stock <= 0 %}</h3>
      <p class = "text-justify my_prod_text" ><b>Out of Stock </b></p>
      {% else %}
      <a class ="btn btn-secondary" href="{% url 'Cart:add_cart' product.id %}">ADD TO CART</a>
      {% endif %}
          </div>
    </div>
{% endblock %}

shop/ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   We have variety of products
{% endblock %}
{% block title %}
   Search
{% endblock %}
{% block content %}
<div>
    <p class = "text-center my_search_text" >You have searched for: <b>"{{query}}"</b></p>
</div>
<div class ="container text-center">
      <div class ="row mx-auto">
          {% for product in products %}
          <div class = "my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
          <div class="card text-center" style="min-width:18rem">
              <a href ="{{product.get_url}}"> <img class = "card-img-top my_image" src = "{{product.image.url}}" alt="all products"></a>
                      <div class = "card-body">
                       <h4><b> {{product.name}}</b></h4>
                       <h4><b>{{product.price}}</b></h4>
                      </div>
                </div>
          </div>
       <div class = "row mx_auto">
           <p class = "text-center my_search_text" > 0 results found</p>
       </div>
          {% endfor %}
      </div>
{% endblock %}
    